export const actionTypes = [
  'Bus',
  'Bought locally',
  'Car share',
  'Composted',
  'Cycled',
  'Clothesline dry',
  'Electric car',
  'Eco-friendly alternative',
  'e-Scooter',
  'Lights off',
  'Metro',
  'Other',
  'Plant-based meal',
  'Protected trees',
  'Recycled',
  'Re-usable coffee cup',
  'Re-usable cup',
  'Re-usable bag',
  'Second hand goods',
  'Tap off',
  'Thrifted clothes',
  'Train',
  'Used leftovers',
  'Unplugged',
  'Vegetarian meal',
  'Walked instead',
  'Pushed instead',
];
